---
# cannot test with docker: /etc/hosts not writable
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: xenial64
    box: bento/ubuntu-16.04

lint:
  name: yamllint
  enabled: False

verifier:
  name: testinfra

provisioner:
  name: ansible
